debug: false
management.endpoints.web.exposure.include: "*"
server:
  port: 8081

logging:
  level:
    com.fastcampus.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: boarduser
    password: board1234
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /restapi
    detection-strategy: annotated # only annotated repos will be exposed by REST API
  thymeleaf3.decoupled-logic: true

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  # paths-to-exclude: /restapi/**
  packages-to-scan: com.fastcampus.board.controller